### PR TITLE
Final Project Submission

### PR DESCRIPTION
**Pull request by amholtz**
This should all work! 

Thanks for a great semester.

### CODE REVIEW

**Comment by rudeboybert** [comment]
Hi Andrew, you forgot to upload the file you call in `obo <- readLines("go.obo.txt")` on line 283.

**Comment by rudeboybert** [comment]
Or can you email me this if there are privacy restrictions?

**Comment by amholtz** [comment]
Sorry about that. It should all be there now. I hadn't really thought about the privacy restrictions. I'm hoping that this is too far into the internet that no one will really find it. Maybe after you look at it, I will copy the repository and make that private.

**Comment by rudeboybert** [comment]
OK, things Knit! Can you leave it up until Thursday afternoon? At that point you can take this one down, and then copy it over to a private repo. Have a nice summer.

**Comment by amholtz** [comment]
Yep! That's fine with me. 

Thanks you too!

**Pull request closed without merging**
